/** @type {string} Set in App after fonts load; defaults keep layout stable */
export const fontFamily = {
    display: 'CormorantGaramond_300Light',
    displayMedium: 'CormorantGaramond_400Regular',
    displaySemi: 'CormorantGaramond_600SemiBold',
    body: 'Outfit_400Regular',
    bodyLight: 'Outfit_300Light',
    bodyMedium: 'Outfit_500Medium',
    bodySemi: 'Outfit_600SemiBold',
};

export const theme = {
    fontFamily,
    colors: {
        primary: '#d4a574',
        primaryGlow: 'rgba(212, 165, 116, 0.5)',
        primaryDark: '#b8894d',
        secondary: '#a855f7',
        secondaryGlow: 'rgba(168, 85, 247, 0.45)',
        accent: '#f0abfc',
        accentGlow: 'rgba(240, 171, 252, 0.4)',
        danger: '#fb7185',
        success: '#6ee7b7',
        warning: '#fcd34d',
        gold: '#e9c46a',
        rose: '#fda4af',
        glassBorder: 'rgba(255, 255, 255, 0.16)',
        glassHighlight: 'rgba(255, 255, 255, 0.28)',
        glassDark: 'rgba(18, 10, 36, 0.58)',
        glassLight: 'rgba(255, 255, 255, 0.72)',
    },
    light: {
        background: '#fff9fb',
        backgroundSecondary: '#faf5ff',
        card: 'rgba(255, 255, 255, 0.78)',
        cardSolid: '#ffffff',
        textMain: '#1e1033',
        textSub: '#7c6b8a',
        border: 'rgba(124, 58, 237, 0.12)',
        meshLine: 'rgba(168, 85, 247, 0.08)',
    },
    dark: {
        background: '#060214',
        backgroundSecondary: '#0f0820',
        card: 'rgba(28, 18, 48, 0.55)',
        cardSolid: '#150d28',
        textMain: '#fcf8ff',
        textSub: '#c4b5d6',
        border: 'rgba(255, 255, 255, 0.1)',
        meshLine: 'rgba(232, 121, 249, 0.06)',
    },
    gradients: {
        darkCanvas: ['#060214', '#120820', '#1a0f2e'],
        darkBlobA: ['#5b21b6', '#a855f7', 'transparent'],
        darkBlobB: ['#9d174d', '#f472b6', 'transparent'],
        darkBlobC: ['#78350f', '#d4a574', 'transparent'],
        lightCanvas: ['#fff9fb', '#faf5ff', '#fffbeb'],
        lightBlobA: ['#e9d5ff', '#f5d0fe', 'transparent'],
        lightBlobB: ['#fce7f3', '#fbcfe8', 'transparent'],
        lightBlobC: ['#fef3c7', '#fde68a', 'transparent'],
        buttonPrimary: ['#7c3aed', '#c026d3', '#d4a574'],
        buttonSecondary: ['#6366f1', '#a78bfa', '#c4b5fd'],
        buttonDanger: ['#db2777', '#fb7185'],
        splashDark: ['#0a0616', '#1a0a2e', '#312e81'],
        auraPink: ['#f0abfc', '#fda4af'],
        auraGold: ['#d4a574', '#fcd34d'],
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 48,
    },
    borderRadius: {
        sm: 16,
        md: 22,
        lg: 26,
        xl: 30,
        xxl: 36,
        full: 9999,
    },
    typography: {
        mega: {
            fontSize: 52,
            fontFamily: fontFamily.display,
            fontWeight: '300',
            letterSpacing: -2,
            lineHeight: 56,
        },
        h1: {
            fontSize: 40,
            fontFamily: fontFamily.display,
            fontWeight: '300',
            letterSpacing: -1.2,
            lineHeight: 44,
        },
        h2: {
            fontSize: 32,
            fontFamily: fontFamily.display,
            fontWeight: '300',
            letterSpacing: -0.8,
            lineHeight: 36,
        },
        h3: {
            fontSize: 22,
            fontFamily: fontFamily.displayMedium,
            fontWeight: '400',
            letterSpacing: -0.2,
            lineHeight: 28,
        },
        subtitle: {
            fontSize: 16,
            fontFamily: fontFamily.bodyMedium,
            fontWeight: '500',
            letterSpacing: 0.2,
        },
        body: {
            fontSize: 16,
            fontFamily: fontFamily.body,
            fontWeight: '400',
            letterSpacing: 0.15,
            lineHeight: 24,
        },
        small: {
            fontSize: 14,
            fontFamily: fontFamily.body,
            fontWeight: '400',
            letterSpacing: 0.1,
        },
        caption: {
            fontSize: 10,
            fontFamily: fontFamily.bodyLight,
            fontWeight: '300',
            letterSpacing: 3.2,
            textTransform: 'uppercase',
        },
        label: {
            fontSize: 11,
            fontFamily: fontFamily.bodySemi,
            fontWeight: '600',
            letterSpacing: 2,
            textTransform: 'uppercase',
        },
    },
    shadows: {
        soft: {
            shadowColor: '#4c1d95',
            shadowOffset: { width: 0, height: 6 },
            shadowOpacity: 0.12,
            shadowRadius: 16,
            elevation: 4,
        },
        medium: {
            shadowColor: '#1e1033',
            shadowOffset: { width: 0, height: 14 },
            shadowOpacity: 0.18,
            shadowRadius: 28,
            elevation: 12,
        },
        glow: (color) => ({
            shadowColor: color,
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.45,
            shadowRadius: 22,
            elevation: 14,
        }),
        innerGlow: {
            shadowColor: '#ffffff',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.25,
            shadowRadius: 1,
        },
    },
};
